// src/pages/todos/index.vue
<template>
    <my-todos
        :todos="todos"
        @update="console.log('EV:', $event)"
        :updateTodos="updateTodos"
    />

    <hr />
    <pre>VUE: {{ todos }}</pre>
</template>

<script>
    console.log('! todos/index')

    import './todos.wc.svelte'

    export default {
        data: () => ({
            todos: [
                { title: 'Item 1' },
                { title: 'Another Item' },
                { title: 'Robot 3' },
            ],
        }),

        methods: {
            updateTodos(newTodos) {
                this.todos = newTodos
                console.log('VUE: update:', this.todos, newTodos)
            },
        },
    }
</script>

// src/pages/todos/todos.wc.svelte
<svelte:options tag="my-todos" />

<script>
    console.log('! todos.wc')
    export let todos = []
    import { createEventDispatcher } from 'svelte';

	const dispatch = createEventDispatcher();
	let me
</script>

<slot name="head">
    <h1>TODOS</h1>
</slot>

<slot>
    {#each todos as item, index}
        <li on:click={e=>{
            todos=todos.filter(i=>i!==item)
            dispatch('update', todos)
        }} >{item} - {index}</li>
    {/each}
    <pre>SVELTE: {todos}</pre>
</slot>

<hr>
SVELTE: $$props: <pre>{JSON.stringify($$props)}</pre>
<hr>
